### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by Pinolinoo** [jfnavarro/st_pipeline#98]
Dear all, 

Sadly I am not able to install the stpipeline. When using pip in a fresh conda env I get the following error: 

` Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/z4/dc80cgy93pj6rgjpx46mnh680000gn/T/pip-install-9dekewms/taggd_cbeca8e7f968423694db01796dba5096/setup.py", line 4, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

When using git clone, also I get an error when running the setup.py. It says it can't find the file in stpipeline/common/cdistance.c which is also not in this directory! 

Happy for your help,
philipp

**Comment by thinkzink** [comment]
You should just run
`pip install numpy`
(with the caveat of this being the latest numpy version rather than any particular one that may be depended upon) before re-executing
